- src/App.css
- src/Container.js
- src/NavTree.js
I think this is better and the code is cleaner.
> Uses MS Fabric components for navigation elements

- src/App.js
- src/classes/Classes.js
- src/classes/actions.js
- src/classes/reducers.js
- src/index.js
- src/indexes/Indexes.js
- src/indexes/actions.js
- src/indexes/reducers.js
- src/nav-tree/NavTree.js
- tests/classes/actions.test.js
- tests/classes/reducers.test.js
- tests/indexes/actions.test.js
- tests/indexes/reducers.test.js
In this PR I moved the classes/indexes data fetching to NavTree so we fetch those data only once. Also I created some unit tests to indexes components
> Move fetching data to NavTree

- src/App.js
- src/index.js
- src/indexes/Indexes.js
- src/secrets/Secrets.js
Fixes: https://github.com/faunadb/sales-engineering/issues/473
Some minor fixes as I'm getting used to the dashboard code.
> Minor fixes

- src/app/App.css
- src/container/Container.js
- src/secrets/Secrets.js
Just so we can refresh the page without losing the previous connection.
> Persist secret and endpoint

- src/index-query/IndexQuery.js
close https://github.com/faunadb/dashboard/issues/5
> paginate query results

- src/app/index.js
- src/authentication/User.js
- src/authentication/login.js
- src/authentication/recognizeUser.js
- src/container/Container.js
- src/index.js
- tests/authentication/login.test.js
- tests/authentication/recognizeUser.test.js
I imagine this is the beginning of our user management system at the dashboard level.
For now I'm faking user auth with local storage api. We'll have to replace this with real authentication once the work on the website is complete.
I'm planing to reflect on the user type to enable intercom widget on a next PR.
> Adding current user to application state

- src/authentication/User.js
- src/authentication/recognizeUser.js
- src/container/Container.js
- src/external/intercom/Lead.js
- src/external/intercom/SDK.js
- src/external/intercom/Widget.js
- tests/authentication/recognizeUser.test.js
- tests/external/intercom/Lead.test.js
Closes: https://github.com/faunadb/sales-engineering/issues/460, https://github.com/faunadb/dashboard/issues/17
I'm still faking user auth through local storage api for now. There is a small styling issue that is causing the chat bubble to appear on top of the repl. I'll fix that in a another PR.
> Initial Intercom widget

- src/classes/index.js
- src/indexes/index.js
close https://github.com/faunadb/dashboard/issues/57
> Fix infinity loop of requests

- src/authentication/SecretForm.js
Apparently redux does not merge nested objects.
> Only clean errors related to the field being changed

- src/classes/ClassInfo.js
- src/nav-tree/NavTree.js
close https://github.com/faunadb/dashboard/issues/69
> dispatch the corresponding selection action when user clicks in the link

- src/index-form/IndexForm.js
> splat should be enough to know when to requery

- src/nav-tree/NavTree.js
fixes https://github.com/faunadb/dashboard/issues/83
> prevent nav tree from spazzing on missing database

- src/discoverKeyType.js
If the dashboard leaves droppings at least they are grouped together.
> Readable nonce

- src/classes/ClassIndexes.js
- src/nav-tree/NavTree.js
fixes https://github.com/faunadb/dashboard/issues/92
> make navtree work for server keys

- src/authentication/index.js
- src/container/Container.js
> reload page on log out

- src/app/App.js
- src/app/clients.js
- src/app/index.js
- src/authentication/SecretForm.js
- src/authentication/index.js
- src/classes/ClassInfo.js
- src/classes/index.js
- src/container/Container.js
- src/databases/index.js
- src/indexes/IndexInfo.js
- src/indexes/index.js
- src/nav-tree/NavTree.js
* removes `componentDidMount` from `ClassInfo` and `IndexInfo`
* uses callback from `Router` to dispatch actions
* transform components into functions
* fixes a minor issue caused when the current database (in url) doesn't exist
> remove method componentDidMount from ClassInfo and IndexInfo

- src/index-query/IndexQuery.js
Closes: https://github.com/faunadb/dashboard/issues/12
I think this is a nice feature to show:
> Implement basic instance history

- src/setupTests.js
forgot to mock `clientForSubDB` in the last PR
> fix broken tests

- package.json
- src/index.js
It will log the states changes as well, but in a very nice way
> logs actions instead of state changes (only in dev mode)

- package.json
- src/app/App.js
- src/authentication/session.js
- src/container/Container.js
- src/setupTests.js
- tests/authentication/restoreSession.test.js
Closes: https://github.com/faunadb/dashboard/issues/44
I think there is a lot of room for improvements in this code but, I'm trying to do just the minimum required for the next release.
> Wire session recognition with website API

- src/index-query/IndexQuery.js
I was getting error about key field in that DetailsList and as per [documentation](https://dev.office.com/fabric#/components/detailslist) that column is required in columns
> add key field to column in DetailsList

- src/app/clients.js
- src/authentication/index.js
- src/discoverKeyType.js
- src/nav-tree/NavTree.js
- tests/authentication/login.test.js
> only discover key type on login

- src/index-query/IndexQuery.js
Fixes: https://github.com/faunadb/dashboard/issues/118
> Do not assume data field is present while getting instances history

- package.json
- src/app/App.js
Fixes: https://github.com/faunadb/dashboard/issues/120
> Adding google analytics for production environment

- src/app/App.js
- src/app/index.js
- src/app/lifecycle.js
- src/authentication/SecretForm.js
- src/authentication/index.js
- tests/app/app.test.js
Calling render before we load the remote session is good, because that can take up to 5 seconds. This avoids the white screen of death in that time.
> render something/anything while we are loading the user session

- src/app/App.js
closes #129 
I know this is ugly, but doing it right will be a lot easier with the new schema tree stuff. Also it's a stop gap until we have a pop-up tour. So it's OK with me thats it's ugly.
> redirect to create a new database on refresh if URL path is basic

- src/app/App.css
- src/container/Container.js
I'd like to deploy this today.
> link to tutorials and documentation

- src/app/App.js
this passes https://faunadb.atlassian.net/wiki/display/SE/Dashboard+acceptance+test+script and fixes an ugly bug. gonna go ahead an deploy, the diff here is against currently deployed dashboard, so I won't be deploying the stuff behind the feature flag yet.
> reload data on page reload. fixes #142

- src/new-dash/dataset/__tests__/special-types.js
- src/new-dash/dataset/components/pagination.css
- src/new-dash/dataset/components/pagination.js
- src/new-dash/dataset/index.js
- src/new-dash/dataset/special-types.js
- src/new-dash/repl/components/editor.css
- src/new-dash/repl/components/editor.js
- src/new-dash/repl/components/toggle-repl.js
- src/new-dash/repl/repl-eval.js
- src/new-dash/schema/__tests__/derived-data.js
- src/new-dash/schema/components/class-info.js
- src/new-dash/schema/components/index-info.js
- src/new-dash/schema/derived-data.js
Closes: https://github.com/fauna/sales-engineering/issues/539
> Add ability to query an index

- src/new-dash/repl/components/editor.js
- src/new-dash/repl/components/toggle-repl.js
> Allow to execute selected code on repl

- src/new-dash/dataset/__tests__/stringify.js
- src/new-dash/dataset/components/instance-info.js
- src/new-dash/dataset/components/pagination.js
- src/new-dash/dataset/components/query-result.js
- src/new-dash/dataset/index.js
- src/new-dash/dataset/stringify.js
- src/new-dash/persistence/faunadb-wrapper.js
- src/new-dash/repl/components/editor.js
- src/new-dash/repl/components/toggle-repl.js
- src/new-dash/schema/components/class-info.js
- src/new-dash/schema/components/index-info.js
Closes: https://github.com/fauna/sales-engineering/issues/556
> Add instance info back

- src/new-dash/schema/components/custom-nav.js
- src/new-dash/schema/components/nav-db-tree.js
- src/new-dash/schema/components/nav-schema.js
Part of: https://github.com/fauna/dashboard/issues/40
> Keep track of selected navigation item

- src/new-dash/router/__tests__/derived-data.js
- src/new-dash/router/derived-data.js
- src/new-dash/schema/__tests__/derived-data.js
- src/new-dash/schema/__tests__/schema-tree.js
- src/new-dash/schema/components/class-info.js
- src/new-dash/schema/components/database-form.js
- src/new-dash/schema/components/delete-form.css
- src/new-dash/schema/components/delete-form.js
- src/new-dash/schema/components/index-info.js
- src/new-dash/schema/derived-data.js
- src/new-dash/schema/schema-tree.js
Closes: https://github.com/fauna/sales-engineering/issues/528
> Add the delete form to databases, classes, and indexes

- src/new-dash/app.js
- src/new-dash/repl/components/toggle-repl.js
- src/new-dash/router/__tests__/derived-data.js
- src/new-dash/router/derived-data.js
- src/new-dash/router/links.js
- src/new-dash/schema/__tests__/derived-data.js
- src/new-dash/schema/components/nav-schema.js
- src/new-dash/schema/derived-data.js
Closes: https://github.com/fauna/dashboard/issues/164
> Add /db as the root url for the new dash

- src/new-dash/repl/components/toggle-repl.js
I've found this small bug while running the acceptance test
> Fix bread crumb order

- src/new-dash/schema/components/class-info.js
- src/new-dash/schema/components/index-info.js
Close: https://github.com/fauna/dashboard/issues/176
> Fix redirect when deleting a class or a index

- src/app/App.js
- src/container/Container.js
- src/new-dash/app.js
- src/new-dash/get-started.js
- src/new-dash/get-started/index.js
closes https://github.com/fauna/sales-engineering/issues/562
copy is:
The developer dashboard allows you to browse and create databases, inspect and define schemas and instances, and explore your data with the interactive query console.
Follow these steps to get comfortable using this dashboard. After each step click the Fauna logo in the top-left corner to get back to this list.
1. Databases are containers for data. You can create as many databases as you like, and they can be nested. Click Create Database in the sidebar to create one.
2. A class is required before you can save data. Each database may contain multiple classes. Instances of a class usually have common structure, but it's OK for their structure to vary. To create a class, navigate via the sidebar to the database you just …
> add documentation to home page and add drivers to header

- package.json
- src/new-dash/repl/query-functions.js
Closes: https://github.com/fauna/dashboard/issues/172
We need it to be fixed as an upgrade require us to also update the `query-functions.js` file.
> Fixing fauna driver version

- src/new-dash/persistence/faunadb-wrapper.js
In production, the exception name gets minified.
Relates to: https://github.com/fauna/faunadb-js/pull/115
> Fixing server key login in prod

- package.json
There was no changes on the query language functions. Just a bug fix.
> Upgrade faunadb-js driver to 0.2.4

- src/index.js
Turning new dashboard on in production.
> Hard code new dashboard on

- src/schema/components/class-form.js
Closes: https://github.com/fauna/dashboard/issues/152
> Redirect to class info after creating a new class

- src/schema/components/database-form.js
- src/schema/components/nav-db-tree.js
Closes: https://github.com/fauna/dashboard/issues/153
> Redirect to class form

- src/authentication/components/login-form.js
Closes: https://github.com/fauna/dashboard/issues/168
> Add link to fauna login at default login form

- package.json
- src/activity-monitor/components/__tests__/__snapshots__/activity-monitor.js.snap
- src/activity-monitor/components/__tests__/activity-monitor.js
- src/authentication/components/__tests__/__snapshots__/user-account.js.snap
- src/authentication/components/__tests__/user-account.js
This is based on the original PR form @marrony: https://github.com/fauna/dashboard/pull/27
It introduces the libraries required for component testing and adds two tests: AcitivityMontor and UserAccount.
As we keep working in the code we should expand the coverage for the rest of the components.
> Component testing

- package.json
> correct package name

- src/external/intercom/sdk.js
- src/repl/components/editor.css
The intercom bubble was not showing at the right place and the repl was not showing at all.
> Fixes for safari

- src/schema/components/fields-form.js
- src/schema/components/index-form.js
just make it a little easier to use
> note about index strategy

- src/schema/components/class-form.js
- src/schema/components/class-info.js
- src/schema/components/database-form.js
- src/schema/components/delete-form.js
- src/schema/components/index-info.js
> more descriptive lables on schema forms

- src/repl/__tests__/repl-eval.js
- src/repl/repl-eval.js
Fixes: #192 
I think this is the further most we can go before adding a AST parser library.
> Allow for multiple statements in the repl

- src/schema/components/__tests__/__snapshots__/nav-schema.js.snap
- src/schema/components/__tests__/nav-schema.js
- src/schema/components/nav-schema.js
> Hide buttons from root db

- src/router/__tests__/links.js
- src/router/links.js
> Fix url encode for resource names

- src/schema/components/__tests__/__snapshots__/keys-manager.js.snap
- src/schema/components/__tests__/keys-manager.js
- src/schema/components/keys-manager.js
> Add note about keys containment

- src/dataset/components/__tests__/__snapshots__/instances-list.js.snap
- src/dataset/components/__tests__/instances-list.js
- src/dataset/components/instance-info.js
- src/dataset/components/instances-list.js
- src/dataset/components/pagination.css
- src/dataset/index.js
- src/schema/__tests__/derived-data.js
- src/schema/components/__tests__/__snapshots__/class-browser.js.snap
- src/schema/components/__tests__/__snapshots__/class-manager.js.snap
- src/schema/components/__tests__/class-browser.js
- src/schema/components/class-browser.js
- src/schema/components/class-instance.js
- src/schema/components/class-manager.js
- src/schema/derived-data.js
Fixes: #202 
When no class index:
Showing data:
When reference is selected:
> Add support for browsing class instances

- src/__tests__/__snapshots__/app.js.snap
- src/__tests__/app.js
- src/activity-monitor/components/activity-monitor.js
- src/app.js
- src/schema/components/__tests__/__snapshots__/nav-tree.js.snap
- src/schema/components/__tests__/nav-tree.js
- src/schema/components/nav-db-tree.js
- src/schema/components/nav-schema.js
- src/schema/components/nav-tree.js
> Hide db tree when using a server key

- src/__tests__/__snapshots__/app.js.snap
- src/app.js
- src/notifications/components/__tests__/__snapshots__/notification-bar.js.snap
- src/notifications/components/__tests__/notification-bar.js
- src/notifications/components/notification-bar.js
- src/notifications/notification-center.js
This was bothering me for a while. Currently, the notification bar makes the page scroll up and down.
It's far from perfect but it's better than before, IMO.
> Move notification bar to the top of the page

- src/authentication/__tests__/session.js
- src/authentication/components/login-form.js
- src/authentication/session.js
- src/notifications/__tests__/notification-center.js
- src/notifications/components/__tests__/__snapshots__/notification-bar.js.snap
- src/notifications/components/__tests__/notification-bar.js
- src/notifications/components/notification-bar.js
- src/notifications/notification-center.js
Currently, we're not checking for points used (or any rules really) so, the message will appear at every login / refresh for cloud users.
I also need feedback on the message and its style, please.
> Ask for billing info on cloud

- src/schema/components/__tests__/__snapshots__/index-browser.js.snap
- src/schema/components/__tests__/__snapshots__/keys-list.js.snap
- src/schema/components/__tests__/index-browser.js
- src/schema/components/__tests__/keys-list.js
- src/schema/components/index-browser.js
- src/schema/components/keys-list.js
So the UI is consistent across schema components.
> Use InstancesList component everywhere

- package.json
- src/index.js
> Enable sentry

- src/schema/components/custom-nav.js
- src/schema/components/nav-db-tree.js
Everyone I show the dashboard asks me how to go back to the root database. Not sure if it's the best approach to solve the problem but, at least, is more visual this way.
> Add root database to the nav-tree

- src/repl/components/toggle-repl.js
Fixes: #223 
During logout there is no fauna client.
> Check for null when updating repl privileges

- src/repl/components/toggle-repl.js
The events should be named `repl-isOpen-true` `repl-fullscreen-false` etc.
> track repl toggles

- package-lock.json
- package.json
- packages/dashboard-base/src/schema/components/fields-form.js
I'm fixing fabric version to avoid bugs introduced on most recent versions. Specially a particularly odd one that makes form submits trigger checkbox "onChange" events and vice versa.
Also, there was a small bug when suggesting terms/values for an index. When `onBlur` was triggered, it entered in a infinite loop.
> DT-16: Fix fabric glitches

- packages/dashboard-base/index.js
- packages/dashboard-base/src/notifications/__tests__/notification-center.js
- packages/dashboard-base/src/notifications/notification-center.js
- packages/dashboard-cloud/src/authentication/auto-login.js
this fixes https://github.com/fauna/dashboard/issues/230 but I haven't been able to test it b/c I don't have the environment to run it with billing options.
> leave billing notice up for an hour

- packages/dashboard-base/src/plugins/events.js
- packages/dashboard-cloud/src/index.js
- packages/dashboard-cloud/src/segment-events.js
Is there a way to test it with the production build?
> Connect Segment track API via wildcard event match

- package-lock.json
- packages/dashboard-cloud/src/intercom/sdk.js
- packages/dashboard-cloud/src/segment-events.js
It seems like intercom has changed their rendered html and that broke our little hack to move the intercom bubble a little up above the the dashboard repl bar.
This PR re-adjusts its position on the screen.
> Fix intercom buble position

- .dockerignore
- Dockerfile
- Dockerfile.release
- Makefile
- README.md
- docker/dashboard.sh
- docker/nginx.conf.template
The default `Dockerfile` is intended for development, a la the Docker tooling for the website, and the `Dockerfile.release` is intended for use in deployments (both production and staging).
> Docker tooling

- package-lock.json
- packages/dashboard-base/package-lock.json
- packages/dashboard-cloud/package-lock.json
I just did a simple wipe and recreate of the package-lock files. This is intended to fix the outstanding security vulnerability GitHub is reporting in this project.
> Update package lock files

- Makefile
> Release tweaks

- Makefile
> SHELLSTATUS is only available in make 4.2+

- packages/dashboard-cloud/src/authentication/cloud-login.js
Part of https://github.com/fauna/website/pull/1317.
> Update cookie name for dashboard

- packages/dashboard-cloud/src/segment-events.js
this will allow us to correlate dashboard events with website events
> segment requires identify() call to happen on client

- packages/dashboard-cloud/src/authentication/auto-login.js
- packages/dashboard-cloud/src/authentication/cloud-login.js
Fixes an infinite redirect when running alongside the website split. I've already placed this into staging.
> Adjust autologin for website split

- packages/dashboard-base/src/schema/components/index-form.js
Correct indexes documentation link to re-direct to the correct link.
> Fix re-direct link bug

- packages/dashboard-base/src/schema/components/__tests__/__snapshots__/keys-form.js.snap
- packages/dashboard-base/src/schema/components/keys-form.js
Correct keys' roles documentation link to re-direct to the correct link.
> Fix redirect link bug

- packages/dashboard-base/src/__tests__/__snapshots__/dashboard.js.snap
Update tests snapshot to add slack link.
> Update dashboard tests snapshot

- public/index.html
PF-63 https://faunadb.atlassian.net/browse/PF-63
> installs gtm tag
