src/persistence/LocalStorage.js
tests/persistence/LocalStorage.test.js

Simple wrapper for local storage API. I'm planing to use this to persist parts of the global state, like the last endpoint and secret used so that we can allow people to refresh the application without asking for these information again.

Add local storage module

---

src/external/intercom/SDK.js

Closes: https://github.com/faunadb/dashboard/issues/61
Intercom stylesheet is loaded asynchronously and all its CSS properties is marked with `!important`. I guess that's an attempt to prevent people from massing with their styles.
I had to do some really dirty hack to fix this.

Fix intercom position

---

src/authentication/SecretForm.js

was getting an Invalid URL error when logging in without specifying a URL. The client has the cloud URL hard-coded so we can pass it as "" or null in our code.

login form should accept an empty URL

---

src/database-form/DatabaseForm.js

`onChanged` has a terrible delay. I usually create databases with half of the name I intended to.

Use onBeforeChange for database form

---

src/database-form/DatabaseForm.js
src/databases/Databases.js

The create database form changes the URL to the new database path.
The delete database form changes the URL to the parent database path.
This exposes some behavior being tracked as #96. Where the class and index names in the nav tree don't redraw. But that but is secondary to this feature, so I think we can merge this now while we fix that.

database forms redirect on success

---

src/persistence/FaunaDB.js

when the notification dispatch is empty, it is still clogging the logs with output. this fixes that.

skip the notification dispatch if there are no notifications

---

src/index-query/IndexQuery.js

Without this fix, the query `q.Get(q.Ref("some/ref/233"))` renders as `Empty result set, no matching data.`.

Fix repl result when the answer is a instance of a class

---

LICENSE
README.md
src/discoverKeyType.js
src/persistence/FaunaDB.js

Bumps copyright date and updates github links for the org change.
Part of https://github.com/fauna/sales-engineering/issues/525.

Update some project info

---

src/new-dash/activity-monitor/components/activity-monitor.css
src/new-dash/activity-monitor/components/activity-monitor.js
src/new-dash/app.css
src/new-dash/app.js
src/new-dash/notifications/components/notification-bar.css
src/new-dash/notifications/components/notification-bar.js
src/new-dash/schema/components/nav-db-tree.js
src/new-dash/schema/components/nav-schema.js
src/new-dash/schema/components/nav-tree.js

Makes the new schema tree a little better:
With activity monitor:
With notifications:
Small screens:
Mostly copy and past from what we've delivered already with some minor adjustments for tablet and phones.

Layout improvements

---

src/new-dash/app.js
src/new-dash/notifications/components/notification-bar.js
src/new-dash/router/__tests__/derived-data.js
src/new-dash/router/__tests__/router.js
src/new-dash/router/derived-data.js
src/new-dash/router/router.js
src/new-dash/schema/__tests__/derived-data.js
src/new-dash/schema/components/class-form.js
src/new-dash/schema/components/database-form.js
src/new-dash/schema/components/nav-db-tree.js
src/new-dash/schema/components/nav-schema.js
src/new-dash/schema/components/schema-form.js
src/new-dash/schema/derived-data.js

As I was working to bring the class info page back I realized the proliferation of selectors I was getting into as more views were coming in.
I took a step back for a bit and tried to compose more useful views out of the `router` and `schema` module so their information is a little more easy to consume from the UI.
Part of: https://github.com/fauna/sales-engineering/issues/531

Improve view of selected resources

---

src/new-dash/dataset/components/query-result.js

So this query works:
```
[
q.Ref("databases"),
"test"
]
```

Minor fix: do not render column if there is no value to render

---

src/new-dash/app.js

Closes: https://github.com/fauna/sales-engineering/issues/552
I'm adding it back as a `process.env.NODE_ENV === "production"` until we figure out how our plugin strategy will be. I imagine this will be extracted out of this source code as well as could login.

Add google analytics back to the new dashboard

---

src/new-dash/schema/__tests__/derived-data.js
src/new-dash/schema/__tests__/schema-tree.js
src/new-dash/schema/components/nav-db-tree.js
src/new-dash/schema/derived-data.js
src/new-dash/schema/schema-tree.js

Establish a pagination strategy for the schema tree according to the follow rules:
- Always load all classes and indexes for the selected database
- When there are more databases than the default pagination size, display a "Load more" button at the navigation tree.

Paginate schema tree

---

src/new-dash/app.js
src/new-dash/schema/__tests__/schema-tree.js
src/new-dash/schema/components/custom-nav.js
src/new-dash/schema/components/nav-db-tree.js
src/new-dash/schema/path.js
src/new-dash/schema/schema-tree.js

Closes: #154, #155
This is an alternative solution to what was proposed at #155.
The original approach was to load the sub-databases information when the user selects a database so we would be able to identify the databases that has nested databases and show the expand icon for them.
This implementation is complex for some reasons:
- It increases the number of calls to the server as a function of the number of nested databases for each level of the schema tree
- If you select a nested database and refresh the page, the only way to keep the schema tree consistent is to not only load the sub-databases but also parent databases up to the root db. Otherwise you have a false notion that you're database tree is loaded but, as you select other levels, more databases show up.
This PR proposes a …

Lazy load database tree as the user navigates through it

---

src/new-dash/notifications/components/notification-bar.js
src/new-dash/notifications/notification-center.js

Scenario:
1. Using fauna cloud
1. Create a class
1. Delete the class
1. Try to create a class with the same name before 60 seconds
Before: 
Now:

Display fauna error messages when notifying about a failure

---

src/index.js

With this two flags, we can test old and new dash in prod even after we force nginx to set the feature flag on by default.

Use two flags to enable or disable new dashboard

---

src/index.js
src/lang/polyfill.js
src/repl/components/editor.css

I've found two browsers incompatibilities:
- `Object.values` is not available in Safari
- Toggle repl was not showing up in Safari

Fix browser compatibility

---

src/authentication/session.js

I can't get the cookie's domain from JS. I think this is the minimum and less risk change we can do now to allow stating test in parallel to website deploys.
The proper fix will come along when we start replacing this with plugins.

Fix subdomain redirect to website urls

---

src/activity-monitor/components/__tests__/__snapshots__/activity-monitor.js.snap
src/activity-monitor/components/__tests__/activity-monitor.js
src/activity-monitor/components/activity-monitor.js
src/authentication/components/__tests__/user-account.js
src/authentication/components/user-account.js
src/schema/components/__tests__/__snapshots__/keys-manager.js.snap
src/schema/components/__tests__/class-delete.js
src/schema/components/__tests__/class-info.js
src/schema/components/__tests__/class-instance.js
src/schema/components/__tests__/keys-form.js
src/schema/components/__tests__/keys-list.js
src/schema/components/__tests__/keys-manager.js
src/schema/components/__tests__/nav-schema.js
src/schema/components/class-delete.js
src/schema/components/class-info.js
src/schema/components/class-instance.js
src/schema/components/keys-form.js
src/schema/components/keys-list.js
src/schema/components/keys-manager.js
src/schema/components/nav-schema.js

I was thinking about the way I've approached component testing recently and I wanted to refactor them a little bit before continue.
They were dependent on redux state, which makes them harder to test as we need to simulate transitions that are already tested by unit tests.
This is an attempt to make component tests isolated from redux state.

Make component tests more isolated

---

src/schema/components/__tests__/__snapshots__/nav-schema.js.snap
src/schema/components/__tests__/nav-schema.js
src/schema/components/nav-schema.js

It was hiding "Create Class" and "Manage Keys" for admin keys, which is incorrect.

Fix permission check: do not hide options based on the tree level

---

src/app.js

I think a merge conflict lead to this. There were 2 notification bars when logging in with a server key.

Remove duplicated NotificationBar when using a server key

---

src/repl/components/editor.js

Fixes: #225, #226 
Since we don't have the necessary modules to support ace find command, it causes an exception.
By disabling it, the default browser text finder will be used.

Disable ace finder since we don't support it

---

src/app.js

If we switch the dashboard's Google Analytics code to use the same one as the fauna.com website, we'll get user and session continuity across the properties. I checked and the rest of the config is already set up properly for that, according to http://www.lunametrics.com/blog/2016/08/11/subdomain-tracking-google-analytics/ 
I think we want to do that. Can anyone think of a reason not to?

use the same analytics code as fauna.com

---

package-lock.json
package.json
packages/dashboard-base/index.js
packages/dashboard-base/package-lock.json
packages/dashboard-base/package.json
packages/dashboard-base/src/__tests__/__snapshots__/dashboard.js.snap
packages/dashboard-base/src/authentication/__tests__/derived-data.js
packages/dashboard-base/src/authentication/__tests__/session.js
packages/dashboard-base/src/authentication/components/login-form.js
packages/dashboard-base/src/authentication/components/user-account.js
packages/dashboard-base/src/authentication/derived-data.js
packages/dashboard-base/src/authentication/session.js
packages/dashboard-base/src/dashboard.js
packages/dashboard-base/src/plugins/components/__tests__/__snapshots__/plugin.js.snap
packages/dashboard-base/src/plugins/components/__tests__/plugin.js
packages/dashboard-base/src/plugins/components/plugin.js
packages/dashboard-base/src/store.js
packages/dashboard-cloud/package-lock.json
packages/dashboard-cloud/package.json
packages/dashboard-cloud/src/authentication/auto-login.js
packages/dashboard-cloud/src/authentication/cloud-login.js
packages/dashboard-cloud/src/authentication/index.js
packages/dashboard-cloud/src/index.js
packages/dashboard-cloud/src/intercom/widget.js

This quite changes the original behaviour as such:
**Base dashboard**:
- Check for credentials in the session store
- If has credentials, skip the login form
- If no credentials, request endpoint and password and save them into the session store
**Cloud Dashboard**:
- Check if there is a website cookie with an auth key
- If have the cookie, calls website API to validate the user
- If has no cookie, redirect user to website login
_Cloud dashboard will never show the login form._

DT-2: Move cloud authentication to cloud dashboard only

---

packages/dashboard-base/src/dataset/components/pagination.js
packages/dashboard-base/src/dataset/components/query-result.js
packages/dashboard-base/src/repl/components/toggle-repl.js

`null` and `false` must be rendered by the `QueryResult` component. Therefore, empty values must be expressed with `undefined` in that case.

DT-15: Render false query results

---

packages/dashboard-base/src/dataset/components/query-result.js

It fixes an error when a query returns a null element. For example: `q.Select(0, [], null)`.

Do not try to read data field from null results

---

packages/dashboard-base/index.js
packages/dashboard-base/src/notifications/__tests__/notification-center.js
packages/dashboard-base/src/notifications/notification-center.js

The original implementation don't account for the interface between the base dashboard and the cloud dashboard.

Make notification interface expose the timeout parameter

---

config/select-package.js
package.json
scripts/build.js
scripts/start.js
scripts/test.js

Fixes #254 
Essentially, we can't set environment variables inline as we do in unix. I'm turning them into arguments for the project scripts.

DT-30: Make npm scripts compatible with windows

---

packages/dashboard-base/src/authentication/session.js

We don't know what will subscribe to these events (including log tools) so we should remove the secret from the event call.

keep client connection data out of the event bus

---

Makefile

CI doesn't have a tty available, so the tests fail to run in that environment. This fixes that.

Don't attach STDIN/tty during test-nowatch

---

Makefile

So we have something stable to refer to each version by.

Tag release images with git sha

---

.dockerignore
Dockerfile
Makefile
docker-compose.yml

Second attempt at fixing the host needing to run `npm install` before the docker image is used for development. This version uses `docker-compose` to configure and run the image, setting up volumes for the 4 `node_modules` folders, which will hold the build deps (running `make clean` will clean these up).
Supersedes https://github.com/fauna/dashboard/pull/265 (`set -e` will be a separate PR).

Use volumes for build dependencies

---

Dockerfile.release
docker/dashboard.sh
docker/nginx.conf.template

Needed for staging, as port 80 will already be in use.

WEB-29: Allow changing the listening port in docker

---

packages/dashboard-base/src/__tests__/__snapshots__/dashboard.js.snap
packages/dashboard-base/src/dashboard.js
packages/dashboard-cloud/src/authentication/auto-login.js

The Application had a fixed billing notification on free trial user's dashboard which seems not to be user-friendly.
The dashboard had two broken links(Tutorials and Drivers) that were redirecting to the documentation page.
Refactored notification code from the auto-login users' code.
Refactored the two codes from the nav code.
Deleted the dashboard snapshot test file and then test the application
Login to Jenkins, from the dashboard, navigate via **website** to **staging**. Click **Build with Parameters** link and set: action: **deploy**, branch: **master**, dashboardBranch: **bg-remove-billing-nag-and-broken-links-NDL-16** and then click **build** button. 
When it finishes building successfully, copy this link [dashboard staging](https://dashboard.website-master.staging.faunadb.net) on …

Bg remove billing nag and broken links ndl 16

---

packages/dashboard-base/src/__tests__/__snapshots__/dashboard.js.snap
packages/dashboard-base/src/dashboard.css
packages/dashboard-base/src/dashboard.js

The dashboard nav width was not consistent with the documentation page nav width.
The dashboard fauna logo was bigger than logos in other application pages.
Decrease the width to match https://fauna.com/documentation
Decrease the size of the logo to match the size of the logo on https://fauna.com/documentation
Login to Jenkins, from the dashboard, navigate via **website** to **staging**. Click **Build with Parameters** link and set: action: **deploy**, branch: **master**, dashboardBranch: **bg-make-account-and-dashboard-navs-consistent-NDL-31** and then click **build** button. 
When it finishes building successfully, copy this link [dashboard staging](https://dashboard.website-master.staging.faunadb.net/db) on the browser to view the implementation.
Before:
After:

Make dashboard navs consistent with other application navs

---

public/index.html

We are not going to bother implementing GTM on the dashboard at this time since it's being completely replaced within the next 1-2 months. The old GA implementation should be sufficient.

remove gtm tag
